// =============================================================================
// strings.typ — Dizionario multilingua del Manuale Utente Avanzato di
// Runtime TelegramBot · Titan Edition. La lingua si sceglie da riga di comando:
// `--input lang=<lang>`. Un solo punto di verità per tutte le stringhe di
// template (copertina, frontespizio, colophon, header, box, indice, capitolo).
// Lingue: it · en · fr · de · es · pt · ru · zh
// I nomi di prodotto "Runtime TelegramBot" e "Titan Edition" restano in latino
// in ogni lingua (marchio). La copertina è vettoriale nativa: si localizza da
// queste stringhe, non servono immagini di copertina per lingua.
// =============================================================================

#let LANG = sys.inputs.at("lang", default: "it")

#let STR = (
  it: (
    typst-lang: "it",
    manual-title: "Manuale Utente Avanzato",
    toc-title: "Indice",
    tagline: "PUBBLICAZIONE AUTOMATICA DA RSS A TELEGRAM",
    aligned-to: "Allineato alla versione",
    version-word: "Versione",
    language-name: "Italiano",
    edition-name: "Seconda Edizione",
    production-word: "Produzione",
    chapter-prefix: "Capitolo ", chapter-suffix: "",
    note-label: "Nota", tip-label: "Suggerimento", warning-label: "⚠ Attenzione",
    rule-label: "Regola d'oro", problem-label: "Problema", solution-label: "Soluzione",
    rights: "Tutti i diritti riservati.",
    repro: "Nessuna parte di questo documento può essere riprodotta, distribuita o trasmessa in qualsiasi forma o con qualsiasi mezzo senza il previo consenso scritto dell'autore.",
    trademark: "Runtime TelegramBot · Titan Edition è un software originale. Telegram, YouTube e gli altri marchi citati appartengono ai rispettivi proprietari.",
    credits: "Software ideato e sviluppato da SIMONE PIZZI. Produzione Ecosystem Runtime. Composto con Typst; titoli in Sora, testo in Inter, codice in Source Code Pro.",
  ),
  en: (
    typst-lang: "en",
    manual-title: "Advanced User Manual",
    toc-title: "Contents",
    tagline: "AUTOMATED RSS-TO-TELEGRAM PUBLISHING",
    aligned-to: "Aligned with version",
    version-word: "Version",
    language-name: "English",
    edition-name: "Second Edition",
    production-word: "Production",
    chapter-prefix: "Chapter ", chapter-suffix: "",
    note-label: "Note", tip-label: "Tip", warning-label: "⚠ Warning",
    rule-label: "Golden Rule", problem-label: "Problem", solution-label: "Solution",
    rights: "All rights reserved.",
    repro: "No part of this document may be reproduced, distributed, or transmitted in any form or by any means without the prior written consent of the author.",
    trademark: "Runtime TelegramBot · Titan Edition is an original software product. Telegram, YouTube and the other trademarks mentioned belong to their respective owners.",
    credits: "Software designed and developed by SIMONE PIZZI. Produced by Ecosystem Runtime. Typeset with Typst; headings in Sora, body in Inter, code in Source Code Pro.",
  ),
  fr: (
    typst-lang: "fr",
    manual-title: "Manuel Utilisateur Avancé",
    toc-title: "Sommaire",
    tagline: "PUBLICATION AUTOMATIQUE DE RSS VERS TELEGRAM",
    aligned-to: "Aligné sur la version",
    version-word: "Version",
    language-name: "Français",
    edition-name: "Deuxième Édition",
    production-word: "Production",
    chapter-prefix: "Chapitre ", chapter-suffix: "",
    note-label: "Note", tip-label: "Conseil", warning-label: "⚠ Attention",
    rule-label: "Règle d'or", problem-label: "Problème", solution-label: "Solution",
    rights: "Tous droits réservés.",
    repro: "Aucune partie de ce document ne peut être reproduite, distribuée ou transmise sous quelque forme ou par quelque moyen que ce soit sans le consentement écrit préalable de l'auteur.",
    trademark: "Runtime TelegramBot · Titan Edition est un logiciel original. Telegram, YouTube et les autres marques citées appartiennent à leurs propriétaires respectifs.",
    credits: "Logiciel conçu et développé par SIMONE PIZZI. Production Ecosystem Runtime. Composé avec Typst ; titres en Sora, texte en Inter, code en Source Code Pro.",
  ),
  de: (
    typst-lang: "de",
    manual-title: "Erweitertes Benutzerhandbuch",
    toc-title: "Inhaltsverzeichnis",
    tagline: "AUTOMATISCHE RSS-ZU-TELEGRAM-VERÖFFENTLICHUNG",
    aligned-to: "Abgestimmt auf Version",
    version-word: "Version",
    language-name: "Deutsch",
    edition-name: "Zweite Auflage",
    production-word: "Produktion",
    chapter-prefix: "Kapitel ", chapter-suffix: "",
    note-label: "Hinweis", tip-label: "Tipp", warning-label: "⚠ Achtung",
    rule-label: "Faustregel", problem-label: "Problem", solution-label: "Lösung",
    rights: "Alle Rechte vorbehalten.",
    repro: "Kein Teil dieses Dokuments darf ohne die vorherige schriftliche Zustimmung des Autors in irgendeiner Form oder mit irgendwelchen Mitteln reproduziert, verbreitet oder übertragen werden.",
    trademark: "Runtime TelegramBot · Titan Edition ist eine eigenständige Software. Telegram, YouTube und die übrigen genannten Marken gehören ihren jeweiligen Eigentümern.",
    credits: "Software konzipiert und entwickelt von SIMONE PIZZI. Produktion Ecosystem Runtime. Gesetzt mit Typst; Überschriften in Sora, Text in Inter, Code in Source Code Pro.",
  ),
  es: (
    typst-lang: "es",
    manual-title: "Manual de Usuario Avanzado",
    toc-title: "Índice",
    tagline: "PUBLICACIÓN AUTOMÁTICA DE RSS A TELEGRAM",
    aligned-to: "Alineado con la versión",
    version-word: "Versión",
    language-name: "Español",
    edition-name: "Segunda Edición",
    production-word: "Producción",
    chapter-prefix: "Capítulo ", chapter-suffix: "",
    note-label: "Nota", tip-label: "Sugerencia", warning-label: "⚠ Atención",
    rule-label: "Regla de oro", problem-label: "Problema", solution-label: "Solución",
    rights: "Todos los derechos reservados.",
    repro: "Ninguna parte de este documento puede ser reproducida, distribuida o transmitida de ninguna forma ni por ningún medio sin el consentimiento previo por escrito del autor.",
    trademark: "Runtime TelegramBot · Titan Edition es un software original. Telegram, YouTube y las demás marcas citadas pertenecen a sus respectivos propietarios.",
    credits: "Software ideado y desarrollado por SIMONE PIZZI. Producción Ecosystem Runtime. Compuesto con Typst; títulos en Sora, texto en Inter, código en Source Code Pro.",
  ),
  pt: (
    typst-lang: "pt",
    manual-title: "Manual do Utilizador Avançado",
    toc-title: "Índice",
    tagline: "PUBLICAÇÃO AUTOMÁTICA DE RSS PARA TELEGRAM",
    aligned-to: "Alinhado com a versão",
    version-word: "Versão",
    language-name: "Português",
    edition-name: "Segunda Edição",
    production-word: "Produção",
    chapter-prefix: "Capítulo ", chapter-suffix: "",
    note-label: "Nota", tip-label: "Dica", warning-label: "⚠ Atenção",
    rule-label: "Regra de ouro", problem-label: "Problema", solution-label: "Solução",
    rights: "Todos os direitos reservados.",
    repro: "Nenhuma parte deste documento pode ser reproduzida, distribuída ou transmitida sob qualquer forma ou por qualquer meio sem o consentimento prévio por escrito do autor.",
    trademark: "Runtime TelegramBot · Titan Edition é um software original. Telegram, YouTube e as restantes marcas citadas pertencem aos respetivos proprietários.",
    credits: "Software concebido e desenvolvido por SIMONE PIZZI. Produção Ecosystem Runtime. Composto com Typst; títulos em Sora, texto em Inter, código em Source Code Pro.",
  ),
  ru: (
    typst-lang: "ru",
    manual-title: "Расширенное руководство пользователя",
    toc-title: "Содержание",
    tagline: "АВТОМАТИЧЕСКАЯ ПУБЛИКАЦИЯ ИЗ RSS В TELEGRAM",
    aligned-to: "Соответствует версии",
    version-word: "Версия",
    language-name: "Русский",
    edition-name: "Второе издание",
    production-word: "Производство",
    chapter-prefix: "Глава ", chapter-suffix: "",
    note-label: "Примечание", tip-label: "Совет", warning-label: "⚠ Внимание",
    rule-label: "Золотое правило", problem-label: "Проблема", solution-label: "Решение",
    rights: "Все права защищены.",
    repro: "Никакая часть этого документа не может быть воспроизведена, распространена или передана в любой форме и любыми средствами без предварительного письменного согласия автора.",
    trademark: "Runtime TelegramBot · Titan Edition — оригинальное программное обеспечение. Telegram, YouTube и другие упомянутые товарные знаки принадлежат их владельцам.",
    credits: "Программа задумана и разработана SIMONE PIZZI. Производство Ecosystem Runtime. Свёрстано в Typst; заголовки — Sora, текст — Inter, код — Source Code Pro.",
  ),
  zh: (
    typst-lang: "zh",
    manual-title: "高级用户手册",
    toc-title: "目录",
    tagline: "从 RSS 到 TELEGRAM 的自动发布",
    aligned-to: "对应版本",
    version-word: "版本",
    language-name: "简体中文",
    edition-name: "第二版",
    production-word: "制作",
    chapter-prefix: "第 ", chapter-suffix: " 章",
    note-label: "注意", tip-label: "提示", warning-label: "⚠ 警告",
    rule-label: "黄金法则", problem-label: "问题", solution-label: "解决方法",
    rights: "保留所有权利。",
    repro: "未经作者事先书面同意，不得以任何形式或任何方式复制、分发或传播本文档的任何部分。",
    trademark: "Runtime TelegramBot · Titan Edition 是一款原创软件。Telegram、YouTube 及文中提及的其他商标均归各自所有者所有。",
    credits: "软件由 SIMONE PIZZI 构思与开发。制作 Ecosystem Runtime。使用 Typst 排版；标题 Sora，正文 Inter，代码 Source Code Pro。",
  ),
)

#let T = STR.at(LANG, default: STR.it)
